const checkOutTypes = {
    MOVE_PRODUCT_TO_CARTS : 'MOVE_PRODUCT_TO_CARTS',
    INCREASE_COUNT_ITEM : 'INCREASE_COUNT_ITEM',
    DECREASE_COUNT_ITEM : 'DECREASE_COUNT_ITEM',
    DELETE_ITEM_FROM_CART : 'DELETE_ITEM_FROM_CART',
    GET_CARTS : 'GET_CARTS',
    EMPTY_CART : 'EMPTY_CART',
    MOVE_TO_CHECKOUT : 'MOVE_TO_CHECKOUT',
    GET_INFO_USER : 'GET_INFO_USER',
    RESET_ALL_CHECKOUT :  'RESET_ALL_CHECKOUT',
    SEND_INFO_CHECKOUT_TO_FIREBASE : 'SEND_INFO_CHECKOUT_TO_FIREBASE'
}
export default checkOutTypes