export {default as Navbar} from './Navbar/Navbar'
export {default as Slide} from './Slide/Slide'
export {default as Announcement} from './Announcement/Announcement'
export {default as Products} from './Products/Products'
export {default as DetailProduct} from './DetailProduct/DetailProduct'
export {default as Newsletter} from './Newsletter/Newsletter'
export {default as Footer} from './Footer/Footer'
