const userTypes = {
    SIGN_UP_WITH_EMAIL : 'SIGN_UP_WITH_EMAIL',
    GET_CURRENT_USER : 'GET_CURRENT_USER',
    SIGN_OUT_USER : 'SIGN_OUT_USER',
    SIGN_IN_WITH_EMAI : 'SIGN_IN_WITH_EMAIL',
    USER_ERROR_LOG_IN : 'USER_ERROR_LOG_IN',
    USER_RESET_ERROR : 'USER_RESET_ERROR',
    USER_RESET_SUCCESS : 'USER_RESET_SUCCESS',
    SIGN_IN_WITH_GOOGLE : 'SIGN_IN_WITH_GOOGLE',
    EDIT_USER_SUCCESS : 'EDIT_USER_SUCCESS'
}

export default userTypes