const productTypes = {
    GET_PRODUCTS : 'GET_PRODUCTS',
    GET_CURRENT_PRODUCT : 'GET_CURRENT_PRODUCT',
    GET_FILTER_PRODUCT  : 'GET_FILTER_PRODUCT',
    FILTER_PRODUCT_START :'FILTER_PRODUCT_START',
    GET_SIMILAR_PRODUCT : 'GET_SIMILAR_PRODUCT',
    GET_CURRENT_ID : 'GET_CURRENT_ID'
}

export default productTypes